StocksAppCleanArchitecture.UI/ViewModels/OrdersViewModel.cs
using Application.DtoModels;


namespace StocksApp.ViewModels
{
	public class OrdersViewModel
	{
		public List<BuyOrderResponse?> BuyOrders { get; set; } = [];
		public List<SellOrderResponse?> SellOrders { get; set; } = [];
	}
}

StocksAppCleanArchitecture.UI/ViewModels/StockDetailsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace StocksApp.ViewModels
{
	public class StockDetailsViewModel
	{
		[Required(ErrorMessage = "Please Enter Quantity")]
		[Range(1, 100000, ErrorMessage = "Quantity must be between 1 and 100000")]
		public int? Quantity { get; set; }
		public string? StockSymbol { get; set; } 
		public string? CompanyName { get; set; }
		public double? Price { get; set; }

		public override string ToString()
		{
			return $"StockDetailsViewModel [Quantity={Quantity}, StockSymbol={StockSymbol}, CompanyName={CompanyName}, Price={Price}]";
		}
	}
}

StocksAppCleanArchitecture.UI/Controllers/StocksAppController.cs
using Application.DtoModels;
using Application.Interfaces;
using Domain.Entities;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Rotativa.AspNetCore;
using Serilog;
using SerilogTimings;
using StocksApp.Factories;
using StocksApp.ViewModels;
namespace StocksApp.Controllers
{
    [Controller]
	[Route("[Controller]")]
	//Parent route
	public class StocksAppController : Controller
	{
		private readonly ILogger<StocksAppController> _logger;
		private readonly IConfiguration _configuration;
		private readonly IFinnhubService _finhubbService;
		private readonly IStocksService _stocksService;
		private readonly ICurrentStockDetails _currentStockDetails;
		private readonly IOptions<TradingOptions> _tradingOptions;
		private readonly IDiagnosticContext _diagnosticContext;

		public StocksAppController(IConfiguration configuration, IFinnhubService finhubbService, IStocksService stocksService, ICurrentStockDetails currentStockDetails, IOptions<TradingOptions> tradingOptions, ILogger<StocksAppController> logger, IDiagnosticContext diagnosticContext)
		{
			_configuration = configuration;
			_finhubbService = finhubbService;
			_stocksService = stocksService;
			_currentStockDetails = currentStockDetails;
			_tradingOptions = tradingOptions;
			_logger = logger;
			_diagnosticContext = diagnosticContext;
		}

		[HttpGet("/")]
		[HttpGet("[Action]")]
		//[HttpGet("[Action]/{stockSymbol}")]
		[GetStockDetailsFilterFactory(1)]
		[LoggerFilterFactory(1, "Called GetStockDetails")]
		public async Task<IActionResult> GetStockDetails(string? stockSymbol, List<string?>? errors, int quantity = 100)
		{

            ViewBag.Errors = errors;

			if (_currentStockDetails.ErrorFlag && stockSymbol == null)
			{
				_currentStockDetails.ErrorFlag = false;
				return View("NoStockFoundError");
			}
			if (stockSymbol is not null || (_currentStockDetails.StockSymbol is null && stockSymbol is null))
			{
				_currentStockDetails.ErrorFlag = false;
				_currentStockDetails.SearchFlag = true;
			}
			if (_currentStockDetails.SearchFlag is true)
			{
				using (Operation.Time("Time For Finnhub Api Response"))
				{
					StockModel? stockModel = await _finhubbService.GetStockInfoAsync(stockSymbol);
					CompanyModel? companyInfo = await _finhubbService.GetCompanyInfoAsync(stockSymbol);

					_currentStockDetails.SearchFlag = false;
					if (stockModel is not null && companyInfo is not null)
					{
						if (stockModel.C is 0 || companyInfo.Name is null || companyInfo.Ticker is null)
						{
							_currentStockDetails.ErrorFlag = true;
							return View("NoStockFoundError");

						}
						StockDetailsViewModel? stockDetailsViewModel = new()
						{
							Quantity = quantity,
							CompanyName = companyInfo.Name,
							StockSymbol = companyInfo.Ticker,
							Price = stockModel.C

						};
						_currentStockDetails.Quantity = quantity;
						_currentStockDetails.StockName = companyInfo.Name;
						_currentStockDetails.StockSymbol = companyInfo.Ticker;
						_currentStockDetails.Price = stockModel.C;

						_diagnosticContext.Set("Stock Details", stockDetailsViewModel);

						return View("StockDetails", stockDetailsViewModel);

					}
				}
			}
			StockDetailsViewModel? currentSockDetailsViewModel = new()
			{
				Quantity = _currentStockDetails.Quantity,
				CompanyName = _currentStockDetails.StockName,
				StockSymbol = _currentStockDetails.StockSymbol,
				Price = _currentStockDetails.Price
			};
			return View("StockDetails", currentSockDetailsViewModel);
		}

		[HttpPost("[Action]")]
		[OrderFilterFactory(2)]
		[LoggerFilterFactory(1, "Called PostOrder")]

		public async Task<IActionResult?> PostOrder(StockDetailsViewModel? stockDetailsViewModel, IFormCollection? form) //IFormCollection? form to collect every possible input in a form and store it in a key-value pair
		{
			if (stockDetailsViewModel is not null && form is not null)
			{
				if (form.ContainsKey("BuyOrder"))
				{

					BuyOrderRequest buyOrderRequest = new()
					{
						StockName = stockDetailsViewModel.CompanyName,
						StockSymbol = stockDetailsViewModel.StockSymbol,
						DateAndTimeOfOrder = DateTime.Now,
						Quantity = (uint?)stockDetailsViewModel.Quantity,
						Price = stockDetailsViewModel.Price,
					};

					await _stocksService.CreateBuyOrderAsync(buyOrderRequest);

				}
				else if (form.ContainsKey("SellOrder"))
				{


					SellOrderRequest sellOrderRequest = new()
					{
						StockName = stockDetailsViewModel.CompanyName,
						StockSymbol = stockDetailsViewModel.StockSymbol,
						DateAndTimeOfOrder = DateTime.Now,
						Quantity = (uint?)stockDetailsViewModel.Quantity,
						Price = stockDetailsViewModel.Price,
					};

					await _stocksService.CreateSellOrderAsync(sellOrderRequest);

				}
				_currentStockDetails.Quantity = stockDetailsViewModel.Quantity;

				return RedirectToAction("GetStockDetails", new { Quantity = stockDetailsViewModel.Quantity });
			}
			return BadRequest();

		}

		[HttpGet("[Action]")]
		[LoggerFilterFactory(1, "Called GetOrders")]

		public async Task<IActionResult?> GetOrders()
		{
            //throw new InvalidOperationException();

            OrdersViewModel ordersViewModel = new()
			{
				BuyOrders = await _stocksService.GetBuyOrdersAsync(),

				SellOrders = await _stocksService.GetSellOrdersAsync()
			};
			return View("Orders", ordersViewModel);
		}
		[HttpGet("[Action]")]
		[LoggerFilterFactory(1, "Called DownladPdf")]

		public async Task<IActionResult> DownloadPdf()
		{

			OrdersViewModel ordersViewModel = new()
			{
				BuyOrders = await _stocksService.GetBuyOrdersAsync(),
				SellOrders = await _stocksService.GetSellOrdersAsync()
			};
			return new ViewAsPdf("OrdersPdf", ordersViewModel, ViewData)
			{
				FileName = "Orders.pdf",
				PageSize = Rotativa.AspNetCore.Options.Size.A4,
				PageOrientation = Rotativa.AspNetCore.Options.Orientation.Portrait
			};
		}
		[HttpGet("[Action]")]
		[LoggerFilterFactory(1, "Called GetExplorePage")]

		public IActionResult? GetExplorePage()
		{
			if (_tradingOptions.Value.CompanyNames is not null && _tradingOptions.Value.Top25PopularStocks is not null)
			{
				CompanyOptionsViewModel companyOptionsViewModel = new()
				{
					CompanyNames = _tradingOptions.Value.CompanyNames.Split(',').ToList(),
					StockSymbols = _tradingOptions.Value.Top25PopularStocks.Split(',').ToList(),
				};
				return View("ExplorePage", companyOptionsViewModel);
			}
			return BadRequest();

		}

		[HttpGet("[Action]")]
		[LoggerFilterFactory(1, "Called GetCompanyAndStockDetailsInExplore")]

		public IActionResult? GetCompanyAndStockDetailsInExplore(string? stockSymbol)
		{

			ViewBag.StockSymbol = stockSymbol;
			if (_tradingOptions.Value.CompanyNames is not null && _tradingOptions.Value.Top25PopularStocks is not null)
			{
				CompanyOptionsViewModel companyOptionsViewModel = new()
				{
					CompanyNames = _tradingOptions.Value.CompanyNames.Split(',').ToList(),
					StockSymbols = _tradingOptions.Value.Top25PopularStocks.Split(',').ToList(),
				};

			
				return View("ExplorePage", companyOptionsViewModel);
			}
			return BadRequest();

		}
		[Route("/Error")]
		public IActionResult ErrorPage()
		{

			IExceptionHandlerPathFeature? exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
			if (exceptionHandlerPathFeature != null && exceptionHandlerPathFeature.Error != null)
			{
				ViewBag.ErrorMessage = exceptionHandlerPathFeature.Error.Message;
			}
			return View("ErrorPage");
		}
	}
}

StocksAppCleanArchitecture.UI/ViewComponents/CompanyAndStockDetailsViewComponent.cs
using Application.Interfaces;
using Domain.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using StocksApp.ExtentionMethods;
using StocksApp.ViewModels;

namespace StocksApp.ViewComponents
{
	public class CompanyAndStockDetailsViewComponent : ViewComponent
	{
		private readonly IFinnhubService _finhubbService;
		private readonly IOptions<TradingOptions> _tradingOptions;

		public CompanyAndStockDetailsViewComponent(IFinnhubService finhubbService, IOptions<TradingOptions> tradingOptions)
		{
			_finhubbService = finhubbService;
			_tradingOptions = tradingOptions;
		}
		public async Task<IViewComponentResult?> InvokeAsync(string stockSymbol)
		{

			StockModel? stockInfo = await _finhubbService.GetStockInfoAsync(stockSymbol);
			CompanyModel? companyInfo = await _finhubbService.GetCompanyInfoAsync(stockSymbol);

			if (companyInfo is not null && stockInfo is not null && companyInfo.AreAllPropertiesNotNull() && stockInfo.AreAllPropertiesNotNull())
			{CompanyAndStockDetails companyAndStockDetails = new()
			{
				Quantity = (int)_tradingOptions.Value.DefaultOrderQuantity,
				CompanyName = companyInfo.Name,
				StockSymbol = companyInfo.Ticker,
				Price = stockInfo.C,
				ImgUrl = companyInfo.Logo,
				Exchange = companyInfo.Exchange,
				FinnhubIndustry = companyInfo.FinnhubIndustry,
			};

				return View("_CompanyAndStockDetails", companyAndStockDetails);
			}
			return View("_Null");
		}
	}
}

StocksAppCleanArchitecture.UI/Views/StocksApp/ErrorPage.cshtml
@{
    ViewBag.Title = "Error";
}

<div class="flex min-h-screen items-center justify-center p-4">
    <div class="mx-auto max-w-lg rounded-lg bg-white p-8 shadow-lg">
        <h1 class="mb-4 text-4xl font-bold text-red-600">Oops!</h1>
        <p class="mb-4 text-lg text-gray-700">Something went wrong. Please try again later.</p>
        <p class="text-sm text-gray-500">
            <strong>Error:</strong> @{
                var errorMessage = ViewBag.ErrorMessage as string;
                if (string.IsNullOrEmpty(errorMessage))
                {
                    errorMessage = "An unknown error occurred.";
                }
                @errorMessage
            }
        </p>
        <a href="/" class="mt-6 inline-block rounded-lg bg-blue-500 px-4 py-2 text-white hover:bg-blue-600">
            Back to Home
        </a>
    </div>
</div>

StocksAppCleanArchitecture.UI/Views/StocksApp/ExplorePage.cshtml
@model CompanyOptionsViewModel
@{
    ViewBag.Title = "Explore";

}
<div class="mt-72 font-bold">
    <ul class="flex text-3xl">
        <li class="mr-6">
            <a asp-controller="StocksApp" asp-action="GetStockDetails" class="text-gray-800 hover:text-blue-800 dark:text-white">Trade</a>
        </li>
        <li class="mr-6">
            <a asp-controller="StocksApp" asp-action="GetOrders" class="text-gray-800 hover:text-blue-800 dark:text-white">Orders</a>
        </li>
        <li class="mr-6">
            <a asp-controller="StocksApp" asp-action="GetExplorePage" class="underline-offset-4 text-gray-800 underline hover:text-blue-800 dark:text-white">Explore</a>
        </li>
    </ul>
</div>
<div class="my-5 text-2xl text-gray-600 dark:text-white">Stocks <span class="text-3xl">▸ </span>Explore</div>

<div class="flex">
    <div class="w-[30rem] block rounded-lg border border-gray-500 bg-white p-6 shadow dark:bg-gray-800 dark:border-gray-700">
        <p class="font-bold text-gray-500">Stocks</p>
        @if (Model.CompanyNames is not null && Model.StockSymbols is not null)
        {
            for (int i = 0; i < Model.StockSymbols.Count; i++)
            {
                <div class="text-lg font-bold dark:text-white">@Model.CompanyNames[i]</div>
                <a asp-controller="StocksApp" asp-action="GetCompanyAndStockDetailsInExplore" asp-route-stockSymbol=@Model.StockSymbols[i] class="underline-offset-4 pb-5 text-gray-500 hover:underline">(@Model.StockSymbols[i])</a>
            }
        }

    </div>

    @if (ViewBag.StockSymbol != null)
    {
        <div class="ml-[10rem]">
            @await Component.InvokeAsync("CompanyAndStockDetails", new { StockSymbol = ViewBag.StockSymbol })
        </div>
    }
</div>

StocksAppCleanArchitecture.UI/Views/StocksApp/NoStockFoundError.cshtml
@{
	ViewBag.Title = "Error No Stock";
}
<div class="mt-72 font-bold">
	<ul class="flex text-3xl">
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetStockDetails" class="underline-offset-4 text-gray-800 underline hover:text-blue-800 dark:text-white">Trade</a>
		</li>
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetOrders" class="text-gray-800 hover:text-blue-800 dark:text-white">Orders</a>
		</li>
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetExplorePage"  class="text-gray-800 hover:text-blue-800 dark:text-white">Explore</a>
		</li>
	</ul>
</div>
<div class="animate-fade-left pb-[50rem] mt-44">
	<div class="block max-w-fit rounded-lg border border-gray-500 bg-white p-6 shadow dark:bg-gray-800 dark:border-gray-700">
		<div class="border-l-2 ml-5 h-auto border-white"></div>
		<div class="ml-5">
			<p class="text-2xl font-bold text-red-500">No Stock Found</p>
		</div>
	</div>
</div>

StocksAppCleanArchitecture.UI/Views/StocksApp/Orders.cshtml
@model OrdersViewModel

@{
	ViewBag.Title = "Orders";
}
<div class="mt-72">

	<ul class="flex text-3xl font-bold">
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetStockDetails" class="text-gray-800 hover:text-blue-800 dark:text-white">Trade</a>
		</li>
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetOrders" class="underline-offset-4 text-gray-800 underline hover:text-blue-800 dark:text-white">Orders</a>
		</li>
		<li class="mr-6">
			<a asp-controller="StocksApp" asp-action="GetExplorePage"  class="text-gray-800 hover:text-blue-800 dark:text-white">Explore</a>
		</li>
	</ul>

	<a asp-controller="StocksApp" asp-action="DownloadPdf" class="mt-10 inline-flex items-center rounded border border-gray-800 bg-gray-100 px-4 py-2 font-bold text-gray-800 hover:bg-gray-800 hover:text-white dark:text-white dark:bg-gray-800 dark:hover:text-gray-800 dark:hover:bg-gray-100">
		<svg class="mr-2 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M13 8V2H7v6H2l8 8 8-8h-5zM0 18h20v2H0v-2z" /></svg>
		<span>Download PDF</span>
	</a>
	<div class="my-5 text-2xl text-gray-600 dark:text-white">Stocks <span class="text-3xl">▸ </span>Orders</div>

	@if (Model.SellOrders is null && Model.BuyOrders is null )
	{
		<div class="text-[3rem] block max-w-fit rounded-lg p-6 text-gray-800 dark:text-white">
			No Orders Yet
		</div>
	}
	else
	{
		<div class="orders pb-[10rem] flex">
			<div>
				@if (Model.BuyOrders is not null)
				{
					<div class="w-[30rem] block rounded-lg border border-gray-500 bg-white p-6 shadow dark:bg-gray-800 dark:border-gray-700">
						<p class="font-bold text-gray-500">Buy Orders</p>

						@foreach (BuyOrderResponse? buyOrderResponse in Model.BuyOrders)
						{
							@await Html.PartialAsync("_BuyOrderBox", buyOrderResponse)

						}
					</div>
				}
				else
				{
					<div class="text-[3rem] block max-w-fit rounded-lg p-6 text-gray-800 dark:text-white">
						No Buy Orders
					</div>
				}
			</div>

			<div class="ml-10">
				@if (Model.SellOrders is not null)
				{
					<div class="w-[30rem] block rounded-lg border border-gray-500 bg-white p-6 shadow dark:bg-gray-800 dark:border-gray-700">
						<p class="font-bold text-gray-500">Sell Orders</p>
						@foreach (SellOrderResponse? sellOrderResponse in Model.SellOrders)
						{
							@await Html.PartialAsync("_SellOrderBox", sellOrderResponse)
						}
					</div>
				}
				else
				{
					<div class="text-[3rem] block max-w-fit rounded-lg p-6 text-gray-800 dark:text-white">
						No Sell Orders
					</div>
				}
			</div>
		</div>
	}
</div>

@section Scripts {
	<script src="/Scripts/GetStockDetailsScript.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="/Scripts/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="/Scripts/jquery.validate.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

StocksAppCleanArchitecture.UI/Views/StocksApp/OrdersPdf.cshtml
@model OrdersViewModel
@{
    Layout = null;
}
<link href=@("http://" + Context.Request.Host.ToString() + "/Css/TailwindOutput.css") rel="stylesheet" />

@if (Model.SellOrders is not null && Model.BuyOrders is not null)
{
    <div class="relative mt-8 overflow-x-auto">
        <h2 class="text-lg font-semibold text-gray-800">Sell Orders</h2>
        <table class="w-full text-left text-sm text-gray-400 rtl:text-right">
            <thead class="bg-gray-700 text-xs uppercase text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Order ID</th>
                    <th scope="col" class="px-6 py-3">Stock Symbol</th>
                    <th scope="col" class="px-6 py-3">Stock Name</th>
                    <th scope="col" class="px-6 py-3">Date and Time of Order</th>
                    <th scope="col" class="px-6 py-3">Quantity</th>
                    <th scope="col" class="px-6 py-3">Price</th>
                    <th scope="col" class="px-6 py-3">Trade Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (SellOrderResponse? sellOrder in Model.SellOrders)
                {
                    if (sellOrder is not null)
                    {
                        <tr class="border-b border-gray-700 bg-gray-800">
                            <th scope="row" class="whitespace-nowrap px-6 py-4 font-medium text-white">
                                @sellOrder.SellOrderID
                            </th>
                            <td class="px-6 py-4">
                                @sellOrder.StockSymbol
                            </td>
                            <td class="px-6 py-4">
                                @sellOrder.StockName
                            </td>
                            <td class="px-6 py-4">
                                @sellOrder.DateAndTimeOfOrder
                            </td>
                            <td class="px-6 py-4">
                                @sellOrder.Quantity
                            </td>
                            <td class="px-6 py-4">
                                @sellOrder.Price
                            </td>
                            <td class="px-6 py-4">
                                @sellOrder.TradeAmount
                            </td>
                        </tr>
                    }

                }
            </tbody>
        </table>
    </div>
    <div class="relative mt-8 overflow-x-auto">
        <h2 class="text-lg font-semibold text-gray-800">Buy Orders</h2>
        <table class="w-full text-left text-sm text-gray-400 rtl:text-right">
            <thead class="bg-gray-700 text-xs uppercase text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Order ID</th>
                    <th scope="col" class="px-6 py-3">Stock Symbol</th>
                    <th scope="col" class="px-6 py-3">Stock Name</th>
                    <th scope="col" class="px-6 py-3">Date and Time of Order</th>
                    <th scope="col" class="px-6 py-3">Quantity</th>
                    <th scope="col" class="px-6 py-3">Price</th>
                    <th scope="col" class="px-6 py-3">Trade Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var buyOrder in Model.BuyOrders)
                {
                    if (buyOrder is not null)
                    {
                        <tr class="border-b border-gray-700 bg-gray-800">
                            <th scope="row" class="whitespace-nowrap px-6 py-4 font-medium text-white">
                                @buyOrder.BuyOrderID
                            </th>
                            <td class="px-6 py-4">
                                @buyOrder.StockSymbol
                            </td>
                            <td class="px-6 py-4">
                                @buyOrder.StockName
                            </td>
                            <td class="px-6 py-4">
                                @buyOrder.DateAndTimeOfOrder
                            </td>
                            <td class="px-6 py-4">
                                @buyOrder.Quantity
                            </td>
                            <td class="px-6 py-4">
                                @buyOrder.Price
                            </td>
                            <td class="px-6 py-4">
                                @buyOrder.TradeAmount
                            </td>
                        </tr>
                    }

                }
            </tbody>
        </table>
    </div>



}

StocksAppCleanArchitecture.UI/Views/StocksApp/StockDetails.cshtml
@model StockDetailsViewModel

@{
    ViewBag.Title = "Home Page";
}
<div class="mt-72 min-h-screen">
    <div class="flex">
        <div>
            <ul class=" flex text-3xl font-bold">
                <li class="mr-6">
                    <a asp-controller="StocksApp" asp-action="GetStockDetails" class="underline-offset-4 text-gray-800 underline hover:text-blue-800 dark:text-white">Trade</a>
                </li>
                <li class="mr-6">
                    <a asp-controller="StocksApp" asp-action="GetOrders" class="text-gray-800 hover:text-blue-800 dark:text-white">Orders</a>
                </li>
                <li class="mr-6">
                    <a asp-controller="StocksApp" asp-action="GetExplorePage" class="text-gray-800 hover:text-blue-800 dark:text-white">Explore</a>
                </li>
            </ul>
            <div class="my-5 text-2xl text-gray-600 dark:text-white">
                Stocks <span class="text-3xl">▸</span> @Model.CompanyName
            </div>
            <div class="animate-fade-left mt-5 block max-w-fit rounded-lg border border-gray-500 bg-white p-6 shadow dark:bg-gray-800 dark:border-gray-700">
                <div class="flex">
                    <div>
                        <h5 class="mb-2 text-3xl font-bold tracking-tight text-gray-900 dark:text-white">@Model.CompanyName (@Model.StockSymbol)</h5>
                        @if (Model.Price is not null)
                        {
                            <p class="text-7xl font-normal text-gray-700 dark:text-gray-400">$<span class="price">@Model.Price.Value.ToString("N")</span></p>
                        }
                    </div>
                    <div class="border-l-2 ml-5 h-auto border-white"></div>
                    <div class="ml-5">
                        <p class="text-2xl font-bold text-gray-500">New Order</p>
                        <form asp-controller="StocksApp" asp-action="PostOrder" method="post" class="mx-auto max-w-sm">
                            <label asp-for="Quantity" class="mb-2 block text-sm font-medium text-gray-900 dark:text-white">Quantity</label>
                            <input asp-for="Quantity" placeholder="99999" class="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" />
                            <div>
                                <span asp-validation-for="Quantity" class="text-l text-red-500 dark:text-red-500"></span>
                            </div>
                            <input type="hidden" asp-for="StockSymbol" />
                            <input type="hidden" asp-for="CompanyName" />
                            <input type="hidden" asp-for="Price" />
                            <button type="submit" name="BuyOrder" value="buy-order-button" class="mb-3 me-2 mt-3 rounded-full bg-green-700 px-5 py-2.5 text-center text-sm font-medium text-white transition delay-150 duration-300 ease-in-out hover:bg-green-800 hover:-translate-y-1 hover:scale-110 focus:outline-none focus:ring-4 focus:ring-green-300 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Buy</button>
                            <button type="submit" name="SellOrder" value="sell-order-button" class="mb-3 me-2 mt-3 rounded-full bg-red-700 px-5 py-2.5 text-center text-sm font-medium text-white transition delay-150 duration-300 ease-in-out hover:bg-red-800 hover:-translate-y-1 hover:scale-110 focus:outline-none focus:ring-4 focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">Sell</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-[50rem] ml-52 mt-40 text-2xl text-white">
            "Stock trading, an age-old practice of buying and selling shares of publicly traded companies, is a dynamic and vital aspect of the financial markets. It all
        </div>
    </div>
</div>

<input type="hidden" id="FinnhubToken" value=@ViewBag.FinnhubToken />
@section Scripts {
    <script src="/Scripts/GetStockDetailsScript.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="/Scripts/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="/Scripts/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="/Scripts/jquery.validate.unobtrusive.min.js"></script>
}